apiVersion: v1
kind: Service
metadata:
  name: basin-w3s
  labels:
    app: basin-w3s
spec:
  selector:
    app: basin-w3s-v1
  ports:
    - name: http
      port: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basin-w3s
  labels:
    app: basin-w3s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basin-w3s-v1
  template:
    metadata:
      labels:
        app: basin-w3s-v1
    spec:
      containers:
        - name: basin-w3s
          image: textile/basin_w3s
          imagePullPolicy: Always
          command: ["./api"]
          env:
            - name: PRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: basin-w3s
                  key: private-key
            - name: PROOF
              valueFrom:
                secretKeyRef:
                  name: basin-w3s
                  key: proof
          envFrom:
            - configMapRef:
                name: configmap-basin-w3s
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3